version: '3'
services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'inventory_service'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'welcome123'
      MYSQL_PASSWORD: 'welcome123'
    ports:
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: inventory-service
    image: inventory-service:latest
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/inventory_service?useSSL=false&allowPublicKeyRetrieval=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: welcome123
    depends_on:
      - mysqldb
volumes:
  db:

